name: ai4bio
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas=2.3.3
  - scikit-learn
  - scikit-image
  - seaborn
  - pytorch
  - torchvision
  - pip
  - pip:
      - ipykernel
      - ipywidgets
      - ipysheet
      - huggingface_hub
      - pyarrow
      - transformers
      - datasets
      - tabulate
      - netgraph
      - mrcfile
      
      

  
