name: semantic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - sentencepiece
    - tiktoken
    - transformers
    - torch
    - torchvision
    - numpy
    - pandas
    - matplotlib
    - huggingface-hub
    - ipykernel
    - jupyterlab
    - scikit-learn
    - scipy
    - tqdm
    - pydantic
